// Adobe MAX 2026 — November 10–12, Los Angeles (PST = UTC−8)
export const MOCK_EVENT_DAYS = ['2026-11-10', '2026-11-11', '2026-11-12'];

// Featured session IDs surfaced in the live carousel when nothing is currently live.
// Covers all three days so the right ones are shown per active day.
export const MOCK_FEATURED_IDS = [
  'k-001', 's-007', 's-001',    // Day 1: opening keynote, design systems, AI workflows
  's-009', 's-010', 's-022',    // Day 2: trends keynote, Express for teams, AE expressions
  's-012', 's-030', 's-013',    // Day 3: closing keynote, design tokens, motion graphics
];

const MOCK_SESSIONS = [
  // ─── DAY 1 (NOV 10) ──────────────────────────────────────────────────────
  {
    id: 'k-001', slug: 'max-keynote-2026', rfCode: 'K001',
    title: 'Adobe MAX 2026 Keynote',
    description: 'The creative conference that puts the world\'s best creative minds on stage. Join us for a spectacular opening keynote featuring major product announcements and inspiring stories from the world\'s top creators.',
    startTimeUtc: '2026-11-10T17:00:00.000Z', endTimeUtc: '2026-11-10T19:00:00.000Z', duration: 120,
    track: 'Featured', type: 'Keynote', technicalLevel: 'All Levels',
    category: 'mainstage', audience: 'All',
    speakers: [
      { name: 'Shantanu Narayen', title: 'CEO, Adobe', photo: 'https://placehold.co/80x80/0066cc/white?text=SN' },
      { name: 'Scott Belsky', title: 'Chief Strategy Officer', photo: 'https://placehold.co/80x80/eb1000/white?text=SB' },
    ],
    products: [], resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/max-keynote-2026', watchUrl: '/max',
    isKeynote: true,
    thumbnailUrl: 'https://placehold.co/560x316/1a1a2e/eb1000?text=MAX+2026+Keynote',
    copyrightDisclaimer: '© 2026 Adobe Inc. All rights reserved.',
  },
  {
    id: 's-001', slug: 'ai-creative-workflows', rfCode: 'S001',
    title: 'AI-Powered Creative Workflows',
    description: 'Discover how Adobe Firefly and Sensei GenAI are transforming creative production. See live demonstrations of generative fill, text-to-image, and automated asset generation inside Photoshop and Illustrator.',
    startTimeUtc: '2026-11-10T19:30:00.000Z', endTimeUtc: '2026-11-10T20:30:00.000Z', duration: 60,
    track: 'Design', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'generative-ai', audience: 'Designer',
    speakers: [{ name: 'Maria Chen', title: 'Principal Designer', photo: 'https://placehold.co/80x80/6b4fbb/white?text=MC' }],
    products: ['Adobe Firefly', 'Adobe Photoshop'],
    resources: [{ title: 'Download slides', url: '/resources/ai-workflows-slides' }],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/ai-creative-workflows', watchUrl: '/max',
    isKeynote: false,
    thumbnailUrl: 'https://placehold.co/560x316/6b4fbb/white?text=AI+Creative+Workflows',
  },

  {
    id: 's-002', slug: 'typography-future', rfCode: 'S002',
    title: 'Typography in the Age of Variable Fonts',
    description: 'Variable fonts have changed everything. Learn how to harness the full expressive range of a single font file to create responsive, animated, and accessible type experiences on the modern web.',
    startTimeUtc: '2026-11-10T21:30:00.000Z', endTimeUtc: '2026-11-10T22:30:00.000Z', duration: 60,
    track: 'Design', type: 'Lab', technicalLevel: 'Advanced',
    category: 'design-and-illustration', audience: 'Designer',
    speakers: [
      { name: 'James Montalbano', title: 'Type Designer', photo: 'https://placehold.co/80x80/009688/white?text=JM' },
      { name: 'Nina Stössinger', title: 'Typographer', photo: 'https://placehold.co/80x80/009688/white?text=NS' },
    ],
    products: ['Adobe Fonts', 'Adobe Illustrator'],
    resources: [{ title: 'Variable font sandbox', url: '/resources/variable-fonts' }],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/typography-future', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-003', slug: 'premiere-pro-speed', rfCode: 'S003',
    title: 'Premiere Pro: Edit Faster',
    description: 'From rough cut to final delivery in record time. This session covers the newest AI-assisted editing tools in Premiere Pro: Speech to Text transcription, auto-reframe, and scene detection.',
    startTimeUtc: '2026-11-10T21:30:00.000Z', endTimeUtc: '2026-11-10T22:30:00.000Z', duration: 60,
    track: 'Video', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'video', audience: 'Content Creator',
    speakers: [{ name: 'Tavita Faleolo', title: 'Senior Video Producer', photo: 'https://placehold.co/80x80/f4811f/white?text=TF' }],
    products: ['Adobe Premiere Pro', 'Adobe After Effects'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/premiere-pro-speed', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-003b', slug: 'lightroom-color-science', rfCode: 'S003B',
    title: 'Color Science in Lightroom: Profiles, Curves & HSL Adjustments for Photographers',
    description: 'Go beyond presets. Learn to read histograms, use tone curves to shape light, and deploy HSL masking for selective hue shifts that hold up in any output medium.',
    startTimeUtc: '2026-11-10T21:30:00.000Z', endTimeUtc: '2026-11-10T22:30:00.000Z', duration: 60,
    track: 'Photography', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'photography', audience: 'Photographer',
    speakers: [{ name: 'Yuna Park', title: 'Commercial Photographer', photo: 'https://placehold.co/80x80/1a7a4a/white?text=YP' }],
    products: ['Adobe Lightroom'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/lightroom-color-science', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-003c', slug: 'uxp-plugins-dev', rfCode: 'S003C',
    title: 'Ship Your First UXP Plugin in 60 Minutes',
    description: 'The Unified Extensibility Platform lets you build Photoshop and InDesign plugins with standard web APIs. We\'ll scaffold, develop, and publish a real plugin from scratch — live.',
    startTimeUtc: '2026-11-10T21:30:00.000Z', endTimeUtc: '2026-11-10T22:30:00.000Z', duration: 60,
    track: 'Developer', type: 'Lab', technicalLevel: 'Advanced',
    category: 'education', audience: 'Developer',
    speakers: [
      { name: 'Alex Torres', title: 'Developer Advocate', photo: 'https://placehold.co/80x80/3d7ab4/white?text=AT' },
      { name: 'Mia Chen', title: 'Platform Engineer', photo: 'https://placehold.co/80x80/3d7ab4/white?text=MC' },
    ],
    products: ['Adobe Photoshop'],
    resources: [{ title: 'Starter repo', url: 'https://github.com/adobe/uxp-starter' }],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/uxp-plugins-dev', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-003d', slug: 'content-supply-chain', rfCode: 'S003D',
    title: 'Scaling Content with Adobe\'s Content Supply Chain',
    description: 'How do the world\'s largest brands produce thousands of on-brand assets per quarter? We\'ll walk through an end-to-end content supply chain using Workfront, Experience Manager, and Express.',
    startTimeUtc: '2026-11-10T21:30:00.000Z', endTimeUtc: '2026-11-10T22:30:00.000Z', duration: 60,
    track: 'Business', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'business', audience: 'Marketing',
    speakers: [{ name: 'Laila Hassan', title: 'Content Ops Lead', photo: 'https://placehold.co/80x80/e01d7a/white?text=LH' }],
    products: ['Adobe Workfront', 'Adobe Experience Manager', 'Adobe Express'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/content-supply-chain', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-004', slug: 'ux-research-synthesis', rfCode: 'S004',
    title: 'From Research to Decisions: UX Synthesis at Scale',
    description: 'User research generates mountains of data. Learn frameworks for synthesizing qualitative and quantitative insights into actionable design decisions that your entire org can align around.',
    startTimeUtc: '2026-11-10T23:00:00.000Z', endTimeUtc: '2026-11-11T00:00:00.000Z', duration: 60,
    track: 'UX', type: 'Workshop', technicalLevel: 'Intermediate',
    category: 'design-and-illustration', audience: 'UX Designer',
    speakers: [{ name: 'Priya Nair', title: 'UX Research Lead', photo: 'https://placehold.co/80x80/e01d7a/white?text=PN' }],
    products: ['Adobe XD'],
    resources: [{ title: 'Synthesis templates', url: '/resources/synthesis-templates' }],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/ux-research-synthesis', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-005', slug: 'substance-3d-shaders', rfCode: 'S005',
    title: 'Hyper-Realistic Materials with Substance 3D',
    description: 'Step inside the material creation pipeline that powers AAA games and Hollywood films. We\'ll build complex PBR shaders from scratch and explore procedural noise, layering, and real-time baking workflows.',
    startTimeUtc: '2026-11-10T23:00:00.000Z', endTimeUtc: '2026-11-11T00:30:00.000Z', duration: 90,
    track: '3D & AR', type: 'Lab', technicalLevel: 'Advanced',
    category: '3d', audience: 'Developer',
    speakers: [{ name: 'Kenji Watanabe', title: '3D Art Director', photo: 'https://placehold.co/80x80/3d7ab4/white?text=KW' }],
    products: ['Adobe Substance 3D'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/substance-3d-shaders', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-005b', slug: 'illustrator-3d-extrude', rfCode: 'S005B',
    title: 'Illustrator 3D & Extrude: Flat Art, Real Depth',
    description: 'The revamped 3D engine in Illustrator lets you extrude, revolve, and inflate vectors with real-time lighting. Learn how to use it to create packaging mockups, icons, and editorial illustrations.',
    startTimeUtc: '2026-11-10T23:00:00.000Z', endTimeUtc: '2026-11-11T00:00:00.000Z', duration: 60,
    track: 'Design', type: 'Breakout', technicalLevel: 'Intermediate',
    category: '3d', audience: 'Designer',
    speakers: [{ name: 'Diana Vargas', title: 'Senior Illustrator', photo: 'https://placehold.co/80x80/6b4fbb/white?text=DV' }],
    products: ['Adobe Illustrator'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/illustrator-3d-extrude', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-005c', slug: 'aem-composability', rfCode: 'S005C',
    title: 'Composable Architecture with AEM',
    description: 'Decouple your CMS from your frontend and unlock faster time-to-market. We cover headless AEM, GraphQL content fragments, and the new App Builder integration for composable commerce.',
    startTimeUtc: '2026-11-10T23:00:00.000Z', endTimeUtc: '2026-11-11T00:00:00.000Z', duration: 60,
    track: 'Developer', type: 'Breakout', technicalLevel: 'Advanced',
    category: 'business', audience: 'Developer',
    speakers: [
      { name: 'Stefan Weber', title: 'AEM Principal Engineer', photo: 'https://placehold.co/80x80/3d7ab4/white?text=SW' },
      { name: 'Fumiko Sato', title: 'Solutions Architect', photo: 'https://placehold.co/80x80/3d7ab4/white?text=FS' },
    ],
    products: ['Adobe Experience Manager'],
    resources: [{ title: 'Composability guide', url: 'https://experienceleague.adobe.com' }],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/aem-composability', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-005d', slug: 'express-social-content', rfCode: 'S005D',
    title: 'Social-First Content Production with Express',
    description: 'Social media teams live or die by velocity. See how to build template libraries in Express that let anyone on the team produce Reels, Stories, and feed posts that stay on-brand at speed.',
    startTimeUtc: '2026-11-10T23:00:00.000Z', endTimeUtc: '2026-11-11T00:00:00.000Z', duration: 60,
    track: 'Business', type: 'Demo', technicalLevel: 'Beginner',
    category: 'social-media', audience: 'Marketing',
    speakers: [{ name: 'Tara Mills', title: 'Social Media Director', photo: 'https://placehold.co/80x80/009688/white?text=TM' }],
    products: ['Adobe Express'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/express-social-content', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-006', slug: 'lightroom-masking-ai', rfCode: 'S006',
    title: 'Masking Revolution: AI Selection in Lightroom',
    description: 'Adobe\'s AI masking tools can detect subjects, skies, backgrounds, and specific objects with one click. This session explores advanced masking workflows for portrait retouching and landscape enhancement.',
    startTimeUtc: '2026-11-11T00:30:00.000Z', endTimeUtc: '2026-11-11T01:30:00.000Z', duration: 60,
    track: 'Photography', type: 'Breakout', technicalLevel: 'Beginner',
    category: 'photography', audience: 'Photographer',
    speakers: [{ name: 'Anita Patel', title: 'Senior Photographer', photo: 'https://placehold.co/80x80/1a7a4a/white?text=AP' }],
    products: ['Adobe Lightroom', 'Adobe Photoshop'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/lightroom-masking-ai', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },

  // ─── DAY 1 — MORNING / PRE-KEYNOTE (will be on-demand by 10am) ───────────
  {
    id: 's-007', slug: 'design-systems-scale', rfCode: 'S007',
    title: 'Design Systems at Scale: Lessons from Adobe Spectrum',
    description: 'How do you maintain a design system used by 200+ product teams? The Spectrum team shares their governance model, token architecture, and component testing strategies that keep things consistent across Adobe\'s product portfolio.',
    startTimeUtc: '2026-11-10T16:30:00.000Z', endTimeUtc: '2026-11-10T17:30:00.000Z', duration: 60,
    track: 'Design', type: 'Breakout', technicalLevel: 'Advanced',
    category: 'branding', audience: 'Designer',
    speakers: [
      { name: 'Robin Rendle', title: 'Design Systems Lead', photo: 'https://placehold.co/80x80/6b4fbb/white?text=RR' },
      { name: 'Daniel Eden', title: 'Design Engineer', photo: 'https://placehold.co/80x80/6b4fbb/white?text=DE' },
    ],
    products: [],
    resources: [{ title: 'Spectrum docs', url: 'https://spectrum.adobe.com' }],
    mrStreamId: null,
    videoAvailable: true, inPerson: false,
    sessionPageUrl: '/sessions/design-systems-scale', watchUrl: '/sessions/design-systems-scale',
    isKeynote: false, thumbnailUrl: 'https://placehold.co/560x316/6b4fbb/white?text=Design+Systems',
  },
  {
    id: 's-008', slug: 'hands-on-3d-workshop', rfCode: 'S008',
    title: 'Hands-On: Sculpting in Substance Modeler and Substance Painter',
    description: 'A convention-floor in-person workshop. Bring your VR headset or use one of our demo stations to sculpt organic forms in Substance Modeler using pressure-sensitive sculpting tools.',
    startTimeUtc: '2026-11-10T16:00:00.000Z', endTimeUtc: '2026-11-10T17:30:00.000Z', duration: 90,
    track: '3D & AR', type: 'Workshop', technicalLevel: 'Intermediate',
    category: '3d', audience: 'Developer',
    speakers: [],
    products: ['Adobe Substance 3D'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: true,
    sessionPageUrl: '/sessions/hands-on-3d-workshop', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },

  // ─── DAY 2 (NOV 11) ──────────────────────────────────────────────────────
  {
    id: 's-009', slug: 'day2-keynote', rfCode: 'K002',
    title: 'Creative Vision: Design Trends for 2027',
    description: 'Every year, leading agencies and brands redefine what\'s possible in visual communication. Our annual trends keynote synthesizes signals from fashion, architecture, games, and digital culture into actionable creative direction.',
    startTimeUtc: '2026-11-11T17:00:00.000Z', endTimeUtc: '2026-11-11T18:30:00.000Z', duration: 90,
    track: 'Featured', type: 'Keynote', technicalLevel: 'All Levels',
    category: 'mainstage', audience: 'All',
    speakers: [{ name: 'Jenna Sparks', title: 'Creative Director, Trend Desk', photo: 'https://placehold.co/80x80/eb1000/white?text=JS' }],
    products: [],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/day2-keynote', watchUrl: '/max',
    isKeynote: true,
    thumbnailUrl: 'https://placehold.co/560x316/1a1a2e/6b4fbb?text=Creative+Vision+2027',
  },
  {
    id: 's-010', slug: 'express-for-teams', rfCode: 'S009',
    title: 'Adobe Express for Enterprise Marketing Teams',
    description: 'Marketing teams need to produce content fast without sacrificing brand consistency. See how Express templates, brand kits, and approval workflows let distributed teams publish on-brand content in minutes.',
    startTimeUtc: '2026-11-11T19:00:00.000Z', endTimeUtc: '2026-11-11T20:00:00.000Z', duration: 60,
    track: 'Design', type: 'Breakout', technicalLevel: 'Beginner',
    category: 'content-creator', audience: 'Marketing',
    speakers: [{ name: 'Lucia Fernandez', title: 'Product Manager, Express', photo: 'https://placehold.co/80x80/009688/white?text=LF' }],
    products: ['Adobe Express'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/express-for-teams', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-011', slug: 'acrobat-ai-assistant', rfCode: 'S010',
    title: 'Acrobat AI Assistant: Document Intelligence',
    description: 'The AI Assistant in Acrobat can summarize 100-page contracts, answer questions across multiple PDFs, and draft replies to document comments. See how enterprises are using it to cut document review time by 60%.',
    startTimeUtc: '2026-11-11T19:00:00.000Z', endTimeUtc: '2026-11-11T20:00:00.000Z', duration: 60,
    track: 'Productivity', type: 'Demo', technicalLevel: 'Beginner',
    category: 'business', audience: 'All',
    speakers: [],
    products: ['Adobe Acrobat'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/acrobat-ai-assistant', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-011b', slug: 'premiere-audio-mixing', rfCode: 'S010B',
    title: 'Audio Mixing for Video Editors in Premiere Pro',
    description: 'You don\'t need to open Audition for every mix. Discover Premiere\'s built-in Essential Sound panel, multi-track mixing, auto-ducking, and loudness normalization to deliver broadcast-ready audio from inside your edit.',
    startTimeUtc: '2026-11-11T19:00:00.000Z', endTimeUtc: '2026-11-11T20:00:00.000Z', duration: 60,
    track: 'Video', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'video', audience: 'Content Creator',
    speakers: [{ name: 'Jerome Baptiste', title: 'Audio Post Supervisor', photo: 'https://placehold.co/80x80/f4811f/white?text=JB' }],
    products: ['Adobe Premiere Pro'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/premiere-audio-mixing', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-011c', slug: 'firefly-api-production', rfCode: 'S010C',
    title: 'Firefly API in Production: Rate Limits, Caching & Cost',
    description: 'Moving from a Firefly prototype to a production pipeline means thinking about throughput, retry logic, and spend. This session shares patterns from teams running Firefly at scale.',
    startTimeUtc: '2026-11-11T19:00:00.000Z', endTimeUtc: '2026-11-11T20:00:00.000Z', duration: 60,
    track: 'Developer', type: 'Breakout', technicalLevel: 'Advanced',
    category: 'generative-ai', audience: 'Developer',
    speakers: [
      { name: 'Omar Shaikh', title: 'Staff Engineer', photo: 'https://placehold.co/80x80/3d7ab4/white?text=OS' },
    ],
    products: ['Adobe Firefly'],
    resources: [{ title: 'API docs', url: 'https://developer.adobe.com/firefly-api' }],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/firefly-api-production', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-011d', slug: 'journey-optimizer-realtime', rfCode: 'S010D',
    title: 'Real-Time Personalization with Adobe Journey Optimizer',
    description: 'Serve the right message at the right moment using AJO\'s real-time decisioning, offer library, and behavioral triggers. Includes a live walkthrough of a web personalization campaign.',
    startTimeUtc: '2026-11-11T19:00:00.000Z', endTimeUtc: '2026-11-11T20:00:00.000Z', duration: 60,
    track: 'Business', type: 'Demo', technicalLevel: 'Intermediate',
    category: 'business', audience: 'Marketing',
    speakers: [{ name: 'Claudia Reyes', title: 'CX Platform Lead', photo: 'https://placehold.co/80x80/e01d7a/white?text=CR' }],
    products: ['Adobe Journey Optimizer'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/journey-optimizer-realtime', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },

  // ─── DAY 2 @ 21:00 UTC: 5 concurrent sessions ────────────────────────────
  {
    id: 's-021', slug: 'photoshop-neural-filters', rfCode: 'S021',
    title: 'Neural Filters Deep Dive: Beyond the Slider',
    description: 'Neural Filters are more than one-click magic. Learn to chain them, mask their output, and blend results with the source image to produce retouching that looks genuinely handcrafted.',
    startTimeUtc: '2026-11-11T21:00:00.000Z', endTimeUtc: '2026-11-11T22:00:00.000Z', duration: 60,
    track: 'Photography', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'photography', audience: 'Photographer',
    speakers: [{ name: 'Ingrid Skov', title: 'Retouching Specialist', photo: 'https://placehold.co/80x80/1a7a4a/white?text=IS' }],
    products: ['Adobe Photoshop'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/photoshop-neural-filters', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-022', slug: 'after-effects-expressions-d2', rfCode: 'S022',
    title: 'After Effects Expressions: Write Less, Animate More',
    description: 'A single expression can replace hours of manual keyframing. This lab covers wiggle, loopOut, time remapping, and linking properties across compositions — all with practical, reusable snippets.',
    startTimeUtc: '2026-11-11T21:00:00.000Z', endTimeUtc: '2026-11-11T22:00:00.000Z', duration: 60,
    track: 'Video', type: 'Lab', technicalLevel: 'Advanced',
    category: 'video', audience: 'Motion Designer',
    speakers: [{ name: 'Paulo Salave\'a', title: 'Motion Design Lead', photo: 'https://placehold.co/80x80/f4811f/white?text=PS' }],
    products: ['Adobe After Effects'],
    resources: [{ title: 'Expression cheat sheet', url: '/resources/ae-expressions' }],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/ae-expressions-d2', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-023', slug: 'rtcdp-audience-activation', rfCode: 'S023',
    title: 'Audience Activation with Real-Time CDP',
    description: 'Stitch identity, build audiences from first-party signals, and push them to paid media destinations in minutes. A practical tour of Real-Time CDP\'s segmentation and activation pipeline.',
    startTimeUtc: '2026-11-11T21:00:00.000Z', endTimeUtc: '2026-11-11T22:00:00.000Z', duration: 60,
    track: 'Business', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'business', audience: 'Marketing',
    speakers: [{ name: 'Fatou Diagne', title: 'Data Activation Strategist', photo: 'https://placehold.co/80x80/e01d7a/white?text=FD' }],
    products: ['Adobe Real-Time CDP'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/rtcdp-audience-activation', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-024', slug: 'indesign-long-doc', rfCode: 'S024',
    title: 'Long Document Mastery in InDesign',
    description: 'Books, annual reports, and technical manuals demand a different skill set. This session covers master pages, styles, data merge, and book files — everything you need to manage a 500-page document without losing your mind.',
    startTimeUtc: '2026-11-11T21:00:00.000Z', endTimeUtc: '2026-11-11T22:00:00.000Z', duration: 60,
    track: 'Design', type: 'Breakout', technicalLevel: 'Advanced',
    category: 'design-and-illustration', audience: 'Designer',
    speakers: [{ name: 'Helena Bergström', title: 'Publication Designer', photo: 'https://placehold.co/80x80/6b4fbb/white?text=HB' }],
    products: ['Adobe InDesign'],
    resources: [{ title: 'Style guide template', url: '/resources/indesign-style-guide' }],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/indesign-long-doc', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-025', slug: 'app-builder-integrations', rfCode: 'S025',
    title: 'App Builder: Extend Adobe Experience Cloud',
    description: 'App Builder lets you build cloud-native apps that run on Adobe infrastructure and integrate natively with AEM, Analytics, and Target. We\'ll ship a working integration in this 60-minute lab.',
    startTimeUtc: '2026-11-11T21:00:00.000Z', endTimeUtc: '2026-11-11T22:00:00.000Z', duration: 60,
    track: 'Developer', type: 'Lab', technicalLevel: 'Advanced',
    category: 'education', audience: 'Developer',
    speakers: [
      { name: 'Ravi Iyer', title: 'Developer Evangelist', photo: 'https://placehold.co/80x80/3d7ab4/white?text=RI' },
      { name: 'Aiko Tanaka', title: 'Platform Architect', photo: 'https://placehold.co/80x80/3d7ab4/white?text=AKT' },
    ],
    products: ['Adobe Experience Manager'],
    resources: [{ title: 'App Builder docs', url: 'https://developer.adobe.com/app-builder' }],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/app-builder-integrations', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },

  // ─── DAY 3 (NOV 12) ──────────────────────────────────────────────────────
  {
    id: 's-012', slug: 'closing-keynote', rfCode: 'K003',
    title: 'The Future of Creativity: Closing Keynote',
    description: 'What does the next decade of creative tools look like? We close MAX 2026 with a look at the research and prototypes shaping where creative software goes next — from spatial computing to AI collaboration to new input modalities.',
    startTimeUtc: '2026-11-12T23:00:00.000Z', endTimeUtc: '2026-11-13T01:00:00.000Z', duration: 120,
    track: 'Featured', type: 'Keynote', technicalLevel: 'All Levels',
    category: 'mainstage', audience: 'All',
    speakers: [{ name: 'Shantanu Narayen', title: 'CEO, Adobe', photo: 'https://placehold.co/80x80/0066cc/white?text=SN' }],
    products: [],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/closing-keynote', watchUrl: '/max',
    isKeynote: true,
    thumbnailUrl: 'https://placehold.co/560x316/0066cc/white?text=Closing+Keynote',
  },
  // ─── DAY 3 @ 19:00 UTC: 5 concurrent sessions ────────────────────────────
  {
    id: 's-030', slug: 'd3-design-tokens', rfCode: 'S030',
    title: 'Design Tokens End-to-End: Figma to Code',
    description: 'Token pipelines eliminate the hand-off gap between design and engineering. Walk through a real token system — from Figma variables through Style Dictionary to component CSS — and see how changes propagate automatically.',
    startTimeUtc: '2026-11-12T19:00:00.000Z', endTimeUtc: '2026-11-12T20:00:00.000Z', duration: 60,
    track: 'Design', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'design-and-illustration', audience: 'Designer',
    speakers: [{ name: 'Sam Bharat', title: 'Design Systems Engineer', photo: 'https://placehold.co/80x80/6b4fbb/white?text=SB' }],
    products: [],
    resources: [{ title: 'Token pipeline repo', url: 'https://github.com/adobe/style-dictionary' }],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/design-tokens', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-031', slug: 'd3-marketo-email', rfCode: 'S031',
    title: 'Email Deliverability & Performance in Marketo Engage',
    description: 'Open rates don\'t mean much if your emails land in spam. This session covers sender reputation, SPF/DKIM/DMARC setup, list hygiene, and A/B testing cadence to systematically improve deliverability.',
    startTimeUtc: '2026-11-12T19:00:00.000Z', endTimeUtc: '2026-11-12T20:00:00.000Z', duration: 60,
    track: 'Business', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'business', audience: 'Marketing',
    speakers: [{ name: 'Aaliya Nkosi', title: 'Email Marketing Specialist', photo: 'https://placehold.co/80x80/e01d7a/white?text=AN' }],
    products: ['Adobe Marketo Engage'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/marketo-email', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-032', slug: 'd3-aero-ar', rfCode: 'S032',
    title: 'World-Scale AR with Adobe Aero',
    description: 'Take AR beyond the phone screen. Build spatially anchored experiences in Adobe Aero that respond to real-world surfaces, lighting, and distance — with zero code required.',
    startTimeUtc: '2026-11-12T19:00:00.000Z', endTimeUtc: '2026-11-12T20:00:00.000Z', duration: 60,
    track: '3D & AR', type: 'Lab', technicalLevel: 'Intermediate',
    category: '3d', audience: 'Designer',
    speakers: [
      { name: 'Bora Kim', title: 'AR Experience Designer', photo: 'https://placehold.co/80x80/3d7ab4/white?text=BK' },
      { name: 'Nadia Osei', title: 'XR Developer', photo: 'https://placehold.co/80x80/3d7ab4/white?text=NO' },
    ],
    products: ['Adobe Aero'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/aero-ar', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-033', slug: 'd3-premiere-collab', rfCode: 'S033',
    title: 'Collaborative Editing in Premiere Pro Productions',
    description: 'Shared Projects are history — Productions let multiple editors work on the same footage library simultaneously without stepping on each other. Learn the folder structure, locking model, and best practices for teams of 5+.',
    startTimeUtc: '2026-11-12T19:00:00.000Z', endTimeUtc: '2026-11-12T20:00:00.000Z', duration: 60,
    track: 'Video', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'video', audience: 'Content Creator',
    speakers: [{ name: 'Marcus Webb', title: 'Post-Production Supervisor', photo: 'https://placehold.co/80x80/f4811f/white?text=MW' }],
    products: ['Adobe Premiere Pro'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/premiere-collab', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-034', slug: 'd3-analytics-cja', rfCode: 'S034',
    title: 'Cross-Channel Attribution with Customer Journey Analytics',
    description: 'CJA stitches together web, app, call center, and in-store data into a single person-level view. See how to build attribution models that finally make your media mix make sense.',
    startTimeUtc: '2026-11-12T19:00:00.000Z', endTimeUtc: '2026-11-12T20:00:00.000Z', duration: 60,
    track: 'Business', type: 'Demo', technicalLevel: 'Advanced',
    category: 'business', audience: 'Marketing',
    speakers: [{ name: 'Theo Andrade', title: 'Analytics Architect', photo: 'https://placehold.co/80x80/009688/white?text=TA' }],
    products: ['Adobe Analytics'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/cja-attribution', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },

  // ─── DAY 3 @ 21:00 UTC: 5 concurrent sessions ────────────────────────────
  {
    id: 's-013', slug: 'after-effects-motion', rfCode: 'S011',
    title: 'Motion Graphics Mastery with After Effects',
    description: 'From kinetic typography to data visualization to broadcast-quality motion graphics — this session is a tour de force through After Effects features that separate good motion designers from great ones.',
    startTimeUtc: '2026-11-12T21:00:00.000Z', endTimeUtc: '2026-11-12T22:00:00.000Z', duration: 60,
    track: 'Video', type: 'Lab', technicalLevel: 'Advanced',
    category: 'video', audience: 'Motion Designer',
    speakers: [{ name: 'Carlos Ruiz', title: 'Motion Design Director', photo: 'https://placehold.co/80x80/f4811f/white?text=CR' }],
    products: ['Adobe After Effects'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/after-effects-motion', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-040', slug: 'd3-photoshop-genai', rfCode: 'S040',
    title: 'Generative Fill Workflows: From Concept to Delivery',
    description: 'Generative Fill isn\'t just for quick fixes — it\'s a full concept-to-delivery workflow. See how art directors are using it to prototype campaign visuals, explore creative directions, and produce final comps without a single stock photo.',
    startTimeUtc: '2026-11-12T21:00:00.000Z', endTimeUtc: '2026-11-12T22:00:00.000Z', duration: 60,
    track: 'Design', type: 'Breakout', technicalLevel: 'Intermediate',
    category: 'generative-ai', audience: 'Designer',
    speakers: [{ name: 'Emi Nakamura', title: 'Creative Director', photo: 'https://placehold.co/80x80/6b4fbb/white?text=EN' }],
    products: ['Adobe Photoshop', 'Adobe Firefly'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/genai-fill-workflows', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-041', slug: 'd3-workfront-reporting', rfCode: 'S041',
    title: 'Workfront Reporting: Executive Dashboards That Matter',
    description: 'Stop exporting to spreadsheets. Build Workfront dashboards that give your CMO real-time visibility into campaign status, resource load, and on-time delivery — without a BI tool.',
    startTimeUtc: '2026-11-12T21:00:00.000Z', endTimeUtc: '2026-11-12T22:00:00.000Z', duration: 60,
    track: 'Business', type: 'Breakout', technicalLevel: 'Beginner',
    category: 'business', audience: 'Marketing',
    speakers: [{ name: 'Simone Leclair', title: 'PMO Director', photo: 'https://placehold.co/80x80/e01d7a/white?text=SL' }],
    products: ['Adobe Workfront'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/workfront-reporting', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-042', slug: 'd3-substance-modeler', rfCode: 'S042',
    title: 'Organic Forms in Substance 3D Modeler',
    description: 'VR sculpting in Substance 3D Modeler lets you feel the volume of your model rather than fighting viewport controls. See how product designers and character artists are using it to compress their concept phase from days to hours.',
    startTimeUtc: '2026-11-12T21:00:00.000Z', endTimeUtc: '2026-11-12T22:00:00.000Z', duration: 60,
    track: '3D & AR', type: 'Lab', technicalLevel: 'Advanced',
    category: '3d', audience: 'Developer',
    speakers: [
      { name: 'Lucas Ferrara', title: 'Character Artist', photo: 'https://placehold.co/80x80/3d7ab4/white?text=LF' },
      { name: 'Yuki Okamoto', title: 'Product Design Lead', photo: 'https://placehold.co/80x80/3d7ab4/white?text=YO' },
    ],
    products: ['Adobe Substance 3D'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/substance-modeler', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
  {
    id: 's-043', slug: 'd3-lightroom-sport', rfCode: 'S043',
    title: 'Sports & Action Photography in Lightroom',
    description: 'Shooting at 30fps generates thousands of keepers. Learn to triage, cull, and batch-process an entire sports shoot — from SDCard to client delivery — in under an hour using Lightroom\'s AI tools.',
    startTimeUtc: '2026-11-12T21:00:00.000Z', endTimeUtc: '2026-11-12T22:00:00.000Z', duration: 60,
    track: 'Photography', type: 'Breakout', technicalLevel: 'Beginner',
    category: 'photography', audience: 'Photographer',
    speakers: [{ name: 'Isaiah Cole', title: 'Sports Photographer', photo: 'https://placehold.co/80x80/1a7a4a/white?text=IC' }],
    products: ['Adobe Lightroom'],
    resources: [],
    mrStreamId: null,
    videoAvailable: false, inPerson: false,
    sessionPageUrl: '/sessions/lightroom-sport', watchUrl: '/max',
    isKeynote: false, thumbnailUrl: null,
  },
];

function normalizeSessions(rawSessions) {
  return rawSessions.map((s) => ({
    id: s.id || '',
    slug: s.slug || '',
    rfCode: s.rfCode || '',
    title: s.title || '',
    description: s.description || '',
    startTimeUtc: s.startTimeUtc || '',
    endTimeUtc: s.endTimeUtc || '',
    duration: s.duration || 0,
    track: s.track || '',
    type: s.type || '',
    technicalLevel: s.technicalLevel || '',
    category: s.category || '',
    audience: s.audience || '',
    speakers: s.speakers || [],
    products: s.products || [],
    resources: s.resources || [],
    mrStreamId: s.mrStreamId ?? null,
    videoAvailable: Boolean(s.videoAvailable),
    inPerson: Boolean(s.inPerson),
    sessionPageUrl: s.sessionPageUrl || '',
    watchUrl: s.watchUrl || '',
    isKeynote: Boolean(s.isKeynote),
    thumbnailUrl: s.thumbnailUrl ?? null,
    ...(s.copyrightDisclaimer ? { copyrightDisclaimer: s.copyrightDisclaimer } : {}),
  }));
}

// TODO: replace with real API call when endpoint is ready
// eslint-disable-next-line no-unused-vars
export async function fetchSessions(apiUrl) {
  return normalizeSessions(MOCK_SESSIONS);
}
